# Stage 1: Build
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

ARG VITE_API_URL
ARG VITE_WALLETCONNECT_PROJECT_ID
ARG VITE_DEBRIDGE_REF
ARG VITE_DEBRIDGE_AFFILIATE_ADDR
ARG VITE_DEBRIDGE_AFFILIATE_PCT

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_WALLETCONNECT_PROJECT_ID=$VITE_WALLETCONNECT_PROJECT_ID
ENV VITE_DEBRIDGE_REF=$VITE_DEBRIDGE_REF
ENV VITE_DEBRIDGE_AFFILIATE_ADDR=$VITE_DEBRIDGE_AFFILIATE_ADDR
ENV VITE_DEBRIDGE_AFFILIATE_PCT=$VITE_DEBRIDGE_AFFILIATE_PCT

RUN npm run build

# Stage 2: Serve with nginx
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
